import { createElement } from 'lwc';
import IMS_InvoiceLines from 'c/iMS_InvoiceLines';

describe('c-i-m-s-invoice-lines', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-i-m-s-invoice-lines', {
            is: IMS_InvoiceLines
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});